name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  install_and_make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install libsfml-dev cmake clang
    - name: Build
      run: cmake .
    - name: Cmake
      run: cmake .
    - name: Make
      run: make
      
